CREATE VIEW
    [dbo].[v_bi_psv]
AS

SELECT 
    PSV_COD
    ,psv_tipo
    ,CASE 
        WHEN LTRIM(RTRIM(UPPER(PSV_VINC))) = 'S' THEN 'SOCIO'
        WHEN LTRIM(RTRIM(UPPER(PSV_VINC))) = 'F' THEN 'FUNCIONARIO'
        WHEN LTRIM(RTRIM(UPPER(PSV_VINC))) = 'P' THEN 'PESSOA FISICA'
        WHEN LTRIM(RTRIM(UPPER(PSV_VINC))) = 'J' THEN 'PESSOA JURIDICA'
        WHEN LTRIM(RTRIM(UPPER(PSV_VINC))) = 'C' THEN 'COOPERATIVADO'
        WHEN LTRIM(RTRIM(UPPER(PSV_VINC))) = 'R' THEN 'RESIDENTE'
        WHEN LTRIM(RTRIM(UPPER(PSV_VINC))) = 'O' THEN 'OUTRO'
     END psv_vinc   
    ,upper(psv_nome) as psv_nome
    
FROM PSV